.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ouch-list 1  "ouch-list " 
.SH NAME
ouch\-list \- List contents of an archive
.SH SYNOPSIS
\fBouch\-list\fR [\fB\-t\fR|\fB\-\-tree\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIARCHIVES\fR> 
.SH DESCRIPTION
List contents of an archive
.SH OPTIONS
.TP
\fB\-t\fR, \fB\-\-tree\fR
Show archive contents as a tree
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIARCHIVES\fR>
Archives whose contents should be listed
